[package]
name = "mngr"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.12"
uuid = { version = "1.8.0" , features = ["v4"]}
chrono = "0.4.38"
clap = "4.5.4"
colored = "2.1.0"
versions = "6.2.0"
serde = { version = "1.0.201", features = ["derive"] }